name: Android Appium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-appium-tests:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: /usr/local/lib/android/sdk/emulator:/usr/local/lib/android/sdk/tools:/usr/local/lib/android/sdk/tools/bin:/usr/local/lib/android/sdk/platform-tools:$PATH

    steps:

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tar unzip openjdk-11-jdk maven

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and resolve dependencies
        run: mvn clean install -DskipTests

      - name: Start Appium server
        run: |
          npm install -g appium
          appium --session-override &

      - name: Run Appium tests
        run: mvn test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: appium-report
          path: target/surefire-reports/
