name: Android Appium Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android-emulator-tests:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: ${{ env.ANDROID_HOME }}/emulator:${{ env.ANDROID_HOME }}/tools:${{ env.ANDROID_HOME }}/tools/bin:${{ env.ANDROID_HOME }}/platform-tools:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "system-images;android-33;google_apis;x86_64" "emulator"

      - name: Start Android emulator
        run: |
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-33;google_apis;x86_64" --force
          nohup emulator -avd test_emulator -no-snapshot -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell input keyevent 82 # unlock screen
        shell: bash

      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Run Appium tests
        run: ./gradlew connectedAndroidTest

      - name: Generate GitHub Actions summary
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const reportPath = 'app/build/reports/androidTests/connected/flavors/debug/index.html';
            if (!fs.existsSync(reportPath)) {
              console.log('Nenhum relatório encontrado, pulando summary.');
              return;
            }
            github.actions.summary.addRaw(`### Android Appium Tests Summary\n[View Report](${reportPath})`).write();
