name: Java Appium Tests

on:
  push:
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      - name: Install Android SDK
        run: |
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R $USER:$USER $ANDROID_HOME
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "emulator" "system-images;android-33;google_apis;x86_64"
          echo "y" | avdmanager create avd -n test_emulator -k "system-images;android-33;google_apis;x86_64" --device "pixel"

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run Appium server
        run: |
          npm install -g appium
          appium --log-level error &
          sleep 10

      - name: Run Tests
        run: mvn test

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-test-report
          path: target/surefire-reports/
