name: Appium Mobile Tests

on:
  push:
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: /usr/local/lib/android/sdk/emulator:/usr/local/lib/android/sdk/tools:/usr/local/lib/android/sdk/tools/bin:/usr/local/lib/android/sdk/platform-tools:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK and Maven
        run: |
          apt-get update
          apt-get install -y unzip tar curl openjdk-11-jdk maven

      - name: Verify Java & Maven
        run: |
          java -version
          mvn -version

      - name: Setup Android SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "emulator"

      - name: Build the project
        run: mvn clean install

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot-load -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run Appium tests
        run: mvn test -Dtest=**/*Test.java

      - name: Collect test reports
        uses: actions/upload-artifact@v4
        with:
          name: appium-reports
          path: target/surefire-reports
