name: Appium Mobile Tests

on:
  push:
  pull_request:

jobs:
  android-appium-tests:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: /usr/local/lib/android/sdk/emulator:/usr/local/lib/android/sdk/tools:/usr/local/lib/android/sdk/tools/bin:/usr/local/lib/android/sdk/platform-tools:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk maven wget unzip tar lib32stdc++6 lib32z1 qemu-kvm

      - name: Verify Java version
        run: java -version

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "emulator" "system-images;android-33;google_apis;x86_64"

      - name: Create Android Emulator
        run: |
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_avd -k "system-images;android-33;google_apis;x86_64" --force
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Start Android Emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd test_avd -no-snapshot -no-audio -no-window &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Start Appium server
        run: |
          npm install -g appium
          nohup appium &

      - name: Run Appium tests (Maven)
        run: mvn clean test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-report
          path: target/surefire-reports
