name: Mobile Automation Appium

on:
  push:
  pull_request:

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window -no-audio -gpu swiftshader_indirect
          cores: 2
          avd-name: test
          emulator-boot-timeout: 600
          disable-animations: true

      - name: Run Appium Tests
        run: mvn clean test
        working-directory: ./appium-tests

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-reports
          path: appium-tests/target/surefire-reports

      - name: Generate GitHub Actions Summary
        if: always()
        run: |
          REPORT_XML="appium-tests/target/surefire-reports/*.xml"
          if compgen -G "$REPORT_XML" > /dev/null; then
            echo "### Appium Tests Summary" >> $GITHUB_STEP_SUMMARY
            for file in $REPORT_XML; do
              TESTS=$(xmllint --xpath "count(//testcase)" $file)
              FAILS=$(xmllint --xpath "count(//testcase[failure])" $file)
              SKIPPED=$(xmllint --xpath "count(//testcase[skipped])" $file)
              echo "- $file: $TESTS tests, $FAILS failed, $SKIPPED skipped" >> $GITHUB_STEP_SUMMARY
            done
          else
            echo "No test reports found." >> $GITHUB_STEP_SUMMARY
        shell: bash
