name: Java Appium Tests

on:
  push:
  pull_request:

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: /usr/local/lib/android/sdk/emulator:/usr/local/lib/android/sdk/tools:/usr/local/lib/android/sdk/tools/bin:/usr/local/lib/android/sdk/platform-tools:$PATH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          build-tools: 33.0.2

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Start Android Emulator
        run: |
          echo "Starting emulator..."
          $ANDROID_HOME/emulator/emulator -avd testAVD -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Build project
        run: ./gradlew clean build

      - name: Run Appium tests
        run: ./gradlew connectedAndroidTest

      - name: Generate GitHub Actions summary
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const reportPath = 'app/build/reports/tests/testDebugUnitTest/testDebugUnitTest.json';
            if (!fs.existsSync(reportPath)) {
              console.log('Nenhum report encontrado, pulando summary.');
              return;
            }
            const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
            let summary = `### Appium Tests Summary\n\n`;
            summary += `| Test | Status |\n| --- | --- |\n`;
            report.testsuites.testsuite.forEach(suite => {
              suite.testcase.forEach(tc => {
                summary += `| ${tc.name} | ${tc.status || 'unknown'} |\n`;
              });
            });
            github.actions.summary.addRaw(summary).write();
